//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblDicCity1
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblDicCity1()
    {
        this.tblHotel1 = new HashSet<tblHotel1>();
    }

    public int DicCityID { get; set; }
    public string DicCountryCode { get; set; }
    public string DicCityCode { get; set; }
    public string DicCityNm { get; set; }
    public string DicCityTC { get; set; }
    public int DicCitySort { get; set; }
    public System.DateTime DicCityADate { get; set; }
    public bool DicCityEnable { get; set; }
    public bool DicCityDel { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblHotel1> tblHotel1 { get; set; }
}

public partial class tblDicRegion1
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblDicRegion1()
    {
        this.tblHotel1 = new HashSet<tblHotel1>();
    }

    public int DicRegionID { get; set; }
    public string DicCountryCode { get; set; }
    public string DicAreaCode { get; set; }
    public string DicRegionCode { get; set; }
    public string DicRegionNm { get; set; }
    public string DicRegionENm { get; set; }
    public int DicRegionSort { get; set; }
    public System.DateTime DicRegionADate { get; set; }
    public bool DicRegionEnable { get; set; }
    public bool DicRegionDel { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblHotel1> tblHotel1 { get; set; }
}

public partial class tblDIYHotelOItem
{
    public int OrderID { get; set; }
    public int RoomProTypeID { get; set; }
    public int HotelRoomID { get; set; }
    public System.DateTime HotelSchSD { get; set; }
    public int OrderRoomPrice { get; set; }
    public int OrderRoomQty { get; set; }
    public int OrderRoomPriceC { get; set; }
    public int OrderRoomQtyC { get; set; }
    public string CheckInTime { get; set; }
    public bool OrderEnable { get; set; }

    public virtual tblDIYOrder tblDIYOrder { get; set; }
    public virtual tblHotelRoomPro1 tblHotelRoomPro1 { get; set; }
}

public partial class tblDIYHotelOU
{
    public int OrderID { get; set; }
    public int UserID { get; set; }
    public int RoomGroup { get; set; }

    public virtual tblDIYOrder tblDIYOrder { get; set; }
    public virtual tblDIYUser tblDIYUser { get; set; }
}

public partial class tblDIYOrder
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblDIYOrder()
    {
        this.tblDIYHotelOItem = new HashSet<tblDIYHotelOItem>();
        this.tblDIYHotelOU = new HashSet<tblDIYHotelOU>();
    }

    public int OrderID { get; set; }
    public int UserID { get; set; }
    public System.DateTime OrderAD { get; set; }
    public int OrderStatus { get; set; }
    public System.DateTime OrderUD { get; set; }
    public Nullable<int> LoginID { get; set; }
    public int OrderPrice { get; set; }
    public Nullable<int> PayPrice { get; set; }
    public string OrderNote { get; set; }
    public string OrderNoteSales { get; set; }
    public string PayID { get; set; }
    public Nullable<System.DateTime> PayTime { get; set; }
    public int PayType { get; set; }
    public int PayStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblDIYHotelOItem> tblDIYHotelOItem { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblDIYHotelOU> tblDIYHotelOU { get; set; }
    public virtual tblDIYUser tblDIYUser { get; set; }
    public virtual tblLoginD tblLogin { get; set; }
}

public partial class tblDIYUser
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblDIYUser()
    {
        this.tblDIYHotelOU = new HashSet<tblDIYHotelOU>();
        this.tblDIYOrder = new HashSet<tblDIYOrder>();
    }

    public int UserID { get; set; }
    public string CFName { get; set; }
    public string CLName { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
    public bool Sex { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblDIYHotelOU> tblDIYHotelOU { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblDIYOrder> tblDIYOrder { get; set; }
    public virtual tblDIYUserExt tblDIYUserExt { get; set; }
}

public partial class tblDIYUserExt
{
    public int UserID { get; set; }
    public string Email { get; set; }
    public string TelH { get; set; }
    public string TelM { get; set; }
    public string Counties { get; set; }
    public string Townships { get; set; }
    public string Addr { get; set; }
    public Nullable<bool> EmailEnable { get; set; }

    public virtual tblDIYUser tblDIYUser { get; set; }
}

public partial class tblHotel1
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblHotel1()
    {
        this.tblHotelImage = new HashSet<tblHotelImage>();
        this.tblHotelRoom1 = new HashSet<tblHotelRoom1>();
    }

    public int HotelID { get; set; }
    public Nullable<int> HiLiteID { get; set; }
    public Nullable<int> LoginID { get; set; }
    public Nullable<int> ProviderID { get; set; }
    public string HotelCoun { get; set; }
    public string HotelCity { get; set; }
    public string HotelLocate { get; set; }
    public string HotelRegion { get; set; }
    public string HotelNm { get; set; }
    public string HotelENm { get; set; }
    public string HotelSNm { get; set; }
    public string HotelCat { get; set; }
    public string HotelClass { get; set; }
    public string HotelURL { get; set; }
    public string HotelRoom { get; set; }
    public string HotelDist { get; set; }
    public string HotelAddr { get; set; }
    public string HotelZip { get; set; }
    public string HotelCDist { get; set; }
    public string HotelCAddr { get; set; }
    public string HotelTelD { get; set; }
    public string HotelTelF { get; set; }
    public string HotelLoc { get; set; }
    public string HotelDetail { get; set; }
    public string HotelFacility { get; set; }
    public int HotelFunction { get; set; }
    public System.DateTime HotelDate { get; set; }
    public bool HotelEnable { get; set; }
    public bool HotelDel { get; set; }
    public int DicCityID { get; set; }
    public int DicRegionID { get; set; }

    public virtual tblDicCity1 tblDicCity { get; set; }
    public virtual tblDicRegion1 tblDicRegion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblHotelImage> tblHotelImage { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblHotelRoom1> tblHotelRoom1 { get; set; }
}

public partial class tblHotelImage
{
    public int ImageID { get; set; }
    public string ImageName { get; set; }
    public string ImageUrl { get; set; }
    public int Sort { get; set; }
    public Nullable<int> HotelID { get; set; }
    public Nullable<int> HotelRoomID { get; set; }
    public bool ImageEnable { get; set; }

    public virtual tblHotel1 tblHotel1 { get; set; }
    public virtual tblHotelRoom1 tblHotelRoom1 { get; set; }
}

public partial class tblHotelRoom1
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblHotelRoom1()
    {
        this.tblHotelImage = new HashSet<tblHotelImage>();
        this.tblHotelSch1 = new HashSet<tblHotelSch1>();
    }

    public int HotelRoomID { get; set; }
    public int HiLiteID { get; set; }
    public int LoginID { get; set; }
    public int HotelID { get; set; }
    public int RoomTypeID { get; set; }
    public string HotelRoomNm { get; set; }
    public string HotelRoomNum { get; set; }
    public string HotelRoomBed { get; set; }
    public string HotelRoomArea { get; set; }
    public string HotelRoomAPPL { get; set; }
    public string HotelRoomFloor { get; set; }
    public string HotelRoomBath { get; set; }
    public string HotelRoomWin { get; set; }
    public string HotelRoomFac { get; set; }
    public int HotelRoomPPL { get; set; }
    public int HotelRoomPrice { get; set; }
    public int HotelRoomSale { get; set; }
    public string HotelRoomNote { get; set; }
    public string HotelRoomNote1 { get; set; }
    public System.DateTime HotelRoomAD { get; set; }
    public System.DateTime HotelRoomUD { get; set; }
    public bool HotelRoomDef { get; set; }
    public bool HotelRoomEnable { get; set; }
    public bool HotelRoomDel { get; set; }

    public virtual tblHotel1 tblHotel1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblHotelImage> tblHotelImage { get; set; }
    public virtual tblHotelRoomType tblHotelRoomType { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblHotelSch1> tblHotelSch1 { get; set; }
}

public partial class tblHotelRoomPro1
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblHotelRoomPro1()
    {
        this.tblDIYHotelOItem = new HashSet<tblDIYHotelOItem>();
    }

    public int RoomProTypeID { get; set; }
    public int HotelRoomID { get; set; }
    public System.DateTime HotelSchSD { get; set; }
    public int HotelProCost { get; set; }
    public int HotelProSale { get; set; }
    public int HotelProPlus { get; set; }
    public int HotelProPlusP { get; set; }
    public System.DateTime HotelProAD { get; set; }
    public System.DateTime HotelProUD { get; set; }
    public bool HotelProEnable { get; set; }
    public int LoginID { get; set; }

    public virtual tblHotelRPType tblHotelRPType { get; set; }
    public virtual tblHotelSch1 tblHotelSch1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblDIYHotelOItem> tblDIYHotelOItem { get; set; }
}

public partial class tblHotelRoomType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblHotelRoomType()
    {
        this.tblHotelRoom1 = new HashSet<tblHotelRoom1>();
    }

    public int RoomTypeID { get; set; }
    public string RoomName { get; set; }
    public string RoomCode { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblHotelRoom1> tblHotelRoom1 { get; set; }
}

public partial class tblHotelRPType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblHotelRPType()
    {
        this.tblHotelRoomPro1 = new HashSet<tblHotelRoomPro1>();
    }

    public int RoomProTypeID { get; set; }
    public string RoomProName { get; set; }
    public string RoomProNote { get; set; }
    public bool RoomProEnable { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblHotelRoomPro1> tblHotelRoomPro1 { get; set; }
}

public partial class tblHotelSch1
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblHotelSch1()
    {
        this.tblHotelRoomPro1 = new HashSet<tblHotelRoomPro1>();
    }

    public int HotelRoomID { get; set; }
    public System.DateTime HotelSchSD { get; set; }
    public int LoginID { get; set; }
    public int HotelSchQty { get; set; }
    public System.DateTime HotelSchAD { get; set; }
    public System.DateTime HotelSchUD { get; set; }
    public bool HotelSchEnable { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblHotelRoomPro1> tblHotelRoomPro1 { get; set; }
    public virtual tblHotelRoom1 tblHotelRoom1 { get; set; }
}

public partial class tblLoginD
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblLoginD()
    {
        this.tblDIYOrder = new HashSet<tblDIYOrder>();
        this.tblMailGroup = new HashSet<tblMailGroup>();
    }

    public int LoginID { get; set; }
    public int HiLiteID { get; set; }
    public string LoginCode { get; set; }
    public string LoginCNm { get; set; }
    public string LoginNm { get; set; }
    public string LoginSex { get; set; }
    public string LoginPWD { get; set; }
    public string LoginEmail { get; set; }
    public string LoginURL { get; set; }
    public string LoginIP { get; set; }
    public string LoginTelD { get; set; }
    public string LoginTelM { get; set; }
    public string LoginYAHOO { get; set; }
    public string LoginMSN { get; set; }
    public string LoginMSN1 { get; set; }
    public string LoginSKYPE { get; set; }
    public int LoginPP { get; set; }
    public string LoginBD { get; set; }
    public string LoginAddr { get; set; }
    public string LoginCP { get; set; }
    public string LoginCT { get; set; }
    public string LoginOD { get; set; }
    public string LoginLD { get; set; }
    public string LoginRole { get; set; }
    public System.DateTime LoginADate { get; set; }
    public bool LoginEnable { get; set; }
    public bool LoginDel { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblDIYOrder> tblDIYOrder { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblMailGroup> tblMailGroup { get; set; }
}

public partial class tblMailGroup
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblMailGroup()
    {
        this.tblLogin = new HashSet<tblLoginD>();
    }

    public int MailGroupID { get; set; }
    public string MailGroupName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblLoginD> tblLogin { get; set; }
}
