//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class BPDataModel2 : DbContext
{
    public BPDataModel2()
        : base("name=BPDataModel2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblDicCity1> tblDicCity1 { get; set; }
    public virtual DbSet<tblDicRegion1> tblDicRegion1 { get; set; }
    public virtual DbSet<tblHotel1> tblHotel1 { get; set; }
    public virtual DbSet<tblHotelImage> tblHotelImage { get; set; }
    public virtual DbSet<tblHotelRoomPro1> tblHotelRoomPro1 { get; set; }
    public virtual DbSet<tblHotelRoomType> tblHotelRoomType { get; set; }
    public virtual DbSet<tblHotelRPType> tblHotelRPType { get; set; }
    public virtual DbSet<tblHotelSch1> tblHotelSch1 { get; set; }
    public virtual DbSet<tblHotelRoom1> tblHotelRoom1 { get; set; }
    public virtual DbSet<tblDIYHotelOItem> tblDIYHotelOItem { get; set; }
    public virtual DbSet<tblDIYHotelOU> tblDIYHotelOU { get; set; }
    public virtual DbSet<tblDIYOrder> tblDIYOrder { get; set; }
    public virtual DbSet<tblDIYUser> tblDIYUser { get; set; }
    public virtual DbSet<tblDIYUserExt> tblDIYUserExt { get; set; }
    public virtual DbSet<tblLoginD> tblLoginD { get; set; }
    public virtual DbSet<tblMailGroup> tblMailGroup { get; set; }
}
