//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class DataModel : DbContext
{
    public DataModel()
        : base("name=DataModel")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<dtproperties> dtproperties { get; set; }
    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    public virtual DbSet<tblAccount> tblAccount { get; set; }
    public virtual DbSet<tblAgent> tblAgent { get; set; }
    public virtual DbSet<tblAgentFile> tblAgentFile { get; set; }
    public virtual DbSet<tblAP10> tblAP10 { get; set; }
    public virtual DbSet<tblAP10A> tblAP10A { get; set; }
    public virtual DbSet<tblAP10His> tblAP10His { get; set; }
    public virtual DbSet<tblAP20> tblAP20 { get; set; }
    public virtual DbSet<tblAP20A> tblAP20A { get; set; }
    public virtual DbSet<tblAP30> tblAP30 { get; set; }
    public virtual DbSet<tblAP30A> tblAP30A { get; set; }
    public virtual DbSet<tblAP60> tblAP60 { get; set; }
    public virtual DbSet<tblAP60A> tblAP60A { get; set; }
    public virtual DbSet<tblAP80A> tblAP80A { get; set; }
    public virtual DbSet<tblAPCheck> tblAPCheck { get; set; }
    public virtual DbSet<tblAPPWA> tblAPPWA { get; set; }
    public virtual DbSet<tblBusiness> tblBusiness { get; set; }
    public virtual DbSet<tblBusinessP> tblBusinessP { get; set; }
    public virtual DbSet<tblDicAD> tblDicAD { get; set; }
    public virtual DbSet<tblDicAir> tblDicAir { get; set; }
    public virtual DbSet<tblDicAirline> tblDicAirline { get; set; }
    public virtual DbSet<tblDicAirPort> tblDicAirPort { get; set; }
    public virtual DbSet<tblDicArea> tblDicArea { get; set; }
    public virtual DbSet<tblDicCal> tblDicCal { get; set; }
    public virtual DbSet<tblDicCat> tblDicCat { get; set; }
    public virtual DbSet<tblDicChild> tblDicChild { get; set; }
    public virtual DbSet<tblDicCity> tblDicCity { get; set; }
    public virtual DbSet<tblDicContinent> tblDicContinent { get; set; }
    public virtual DbSet<tblDicCountry> tblDicCountry { get; set; }
    public virtual DbSet<tblDicCurrency> tblDicCurrency { get; set; }
    public virtual DbSet<tblDicDist> tblDicDist { get; set; }
    public virtual DbSet<tblDicEdu> tblDicEdu { get; set; }
    public virtual DbSet<tblDicImage> tblDicImage { get; set; }
    public virtual DbSet<tblDicJob> tblDicJob { get; set; }
    public virtual DbSet<tblDicLocate> tblDicLocate { get; set; }
    public virtual DbSet<tblDicMap> tblDicMap { get; set; }
    public virtual DbSet<tblDicMarriage> tblDicMarriage { get; set; }
    public virtual DbSet<tblDicPlace> tblDicPlace { get; set; }
    public virtual DbSet<tblDicQues> tblDicQues { get; set; }
    public virtual DbSet<tblDicRegion> tblDicRegion { get; set; }
    public virtual DbSet<tblDicSchedule> tblDicSchedule { get; set; }
    public virtual DbSet<tblDicTranslate> tblDicTranslate { get; set; }
    public virtual DbSet<tblDicVisa> tblDicVisa { get; set; }
    public virtual DbSet<tblDicWage> tblDicWage { get; set; }
    public virtual DbSet<tblHiLite> tblHiLite { get; set; }
    public virtual DbSet<tblHistory> tblHistory { get; set; }
    public virtual DbSet<tblHotel> tblHotel { get; set; }
    public virtual DbSet<tblHotelKNT> tblHotelKNT { get; set; }
    public virtual DbSet<tblHotelPackageD> tblHotelPackageD { get; set; }
    public virtual DbSet<tblHotelPackageR> tblHotelPackageR { get; set; }
    public virtual DbSet<tblHotelRoom> tblHotelRoom { get; set; }
    public virtual DbSet<tblHotelSch> tblHotelSch { get; set; }
    public virtual DbSet<tblHotelTour> tblHotelTour { get; set; }
    public virtual DbSet<tblHotelTourD> tblHotelTourD { get; set; }
    public virtual DbSet<tblHotelTourR> tblHotelTourR { get; set; }
    public virtual DbSet<tblImage> tblImage { get; set; }
    public virtual DbSet<tblInvoice> tblInvoice { get; set; }
    public virtual DbSet<tblInvoiceD> tblInvoiceD { get; set; }
    public virtual DbSet<tblLogin> tblLogin { get; set; }
    public virtual DbSet<tblLoginAuth> tblLoginAuth { get; set; }
    public virtual DbSet<tblLoginGP> tblLoginGP { get; set; }
    public virtual DbSet<tblLoginGS> tblLoginGS { get; set; }
    public virtual DbSet<tblLoginGU> tblLoginGU { get; set; }
    public virtual DbSet<tblLoginHis> tblLoginHis { get; set; }
    public virtual DbSet<tblLoginSec> tblLoginSec { get; set; }
    public virtual DbSet<tblMember> tblMember { get; set; }
    public virtual DbSet<tblMemberBonus> tblMemberBonus { get; set; }
    public virtual DbSet<tblMemberD> tblMemberD { get; set; }
    public virtual DbSet<tblMemberDoc> tblMemberDoc { get; set; }
    public virtual DbSet<tblMemberHis> tblMemberHis { get; set; }
    public virtual DbSet<tblMemOrder> tblMemOrder { get; set; }
    public virtual DbSet<tblNews> tblNews { get; set; }
    public virtual DbSet<tblNewsCat> tblNewsCat { get; set; }
    public virtual DbSet<tblOrder> tblOrder { get; set; }
    public virtual DbSet<tblOrderCash> tblOrderCash { get; set; }
    public virtual DbSet<tblOrderCus> tblOrderCus { get; set; }
    public virtual DbSet<tblOrderHis> tblOrderHis { get; set; }
    public virtual DbSet<tblOrderPaid> tblOrderPaid { get; set; }
    public virtual DbSet<tblOrderPro> tblOrderPro { get; set; }
    public virtual DbSet<tblOrderProD> tblOrderProD { get; set; }
    public virtual DbSet<tblOrderTmp> tblOrderTmp { get; set; }
    public virtual DbSet<tblOrderVisa> tblOrderVisa { get; set; }
    public virtual DbSet<tblProduct> tblProduct { get; set; }
    public virtual DbSet<tblProductAir> tblProductAir { get; set; }
    public virtual DbSet<tblProductAirSch> tblProductAirSch { get; set; }
    public virtual DbSet<tblProductCat> tblProductCat { get; set; }
    public virtual DbSet<tblProductCount> tblProductCount { get; set; }
    public virtual DbSet<tblProductDetail> tblProductDetail { get; set; }
    public virtual DbSet<tblProductDoc> tblProductDoc { get; set; }
    public virtual DbSet<tblProductFile> tblProductFile { get; set; }
    public virtual DbSet<tblProductHtl> tblProductHtl { get; set; }
    public virtual DbSet<tblProductHtlSch> tblProductHtlSch { get; set; }
    public virtual DbSet<tblProductO> tblProductO { get; set; }
    public virtual DbSet<tblProductOpt> tblProductOpt { get; set; }
    public virtual DbSet<tblProductP> tblProductP { get; set; }
    public virtual DbSet<tblProductPromo> tblProductPromo { get; set; }
    public virtual DbSet<tblProductSch> tblProductSch { get; set; }
    public virtual DbSet<tblProductSchCar> tblProductSchCar { get; set; }
    public virtual DbSet<tblProductSchD> tblProductSchD { get; set; }
    public virtual DbSet<tblProductSchM> tblProductSchM { get; set; }
    public virtual DbSet<tblProductSchOKA> tblProductSchOKA { get; set; }
    public virtual DbSet<tblProductSchT> tblProductSchT { get; set; }
    public virtual DbSet<tblProductSight> tblProductSight { get; set; }
    public virtual DbSet<tblProductTI> tblProductTI { get; set; }
    public virtual DbSet<tblProductUrl> tblProductUrl { get; set; }
    public virtual DbSet<tblProductVisa> tblProductVisa { get; set; }
    public virtual DbSet<tblProfit> tblProfit { get; set; }
    public virtual DbSet<tblProfitD> tblProfitD { get; set; }
    public virtual DbSet<tblProvider> tblProvider { get; set; }
    public virtual DbSet<tblProviderFile> tblProviderFile { get; set; }
    public virtual DbSet<tblReproTBoss> tblReproTBoss { get; set; }
    public virtual DbSet<tblSalesRec> tblSalesRec { get; set; }
    public virtual DbSet<tblSalesRecB> tblSalesRecB { get; set; }
    public virtual DbSet<tblSalesRecH> tblSalesRecH { get; set; }
    public virtual DbSet<tblSalesRecL> tblSalesRecL { get; set; }
    public virtual DbSet<tblSalesRecLG> tblSalesRecLG { get; set; }
    public virtual DbSet<tblSight> tblSight { get; set; }
    public virtual DbSet<tblSightCat> tblSightCat { get; set; }
    public virtual DbSet<tblSightImg> tblSightImg { get; set; }
    public virtual DbSet<tblSightSeeing> tblSightSeeing { get; set; }
    public virtual DbSet<tblTourGuide> tblTourGuide { get; set; }
    public virtual DbSet<tblTourGuideImg> tblTourGuideImg { get; set; }
    public virtual DbSet<tblTR30> tblTR30 { get; set; }
    public virtual DbSet<tblTranH> tblTranH { get; set; }
    public virtual DbSet<tblTravelAgnt> tblTravelAgnt { get; set; }
    public virtual DbSet<tblUUPON> tblUUPON { get; set; }
    public virtual DbSet<tblAP80> tblAP80 { get; set; }
    public virtual DbSet<tblAPCash> tblAPCash { get; set; }
    public virtual DbSet<tblAPPW> tblAPPW { get; set; }
    public virtual DbSet<tblMemberDDel> tblMemberDDel { get; set; }
    public virtual DbSet<tblProductExpo> tblProductExpo { get; set; }
    public virtual DbSet<tblProductTI1> tblProductTI1 { get; set; }
    public virtual DbSet<tblSightRev> tblSightRev { get; set; }
    public virtual DbSet<tblTourBook1> tblTourBook1 { get; set; }
    public virtual DbSet<tblTourBook1TI> tblTourBook1TI { get; set; }
    public virtual DbSet<tblTourBook2> tblTourBook2 { get; set; }
    public virtual DbSet<tblTourBook2TI> tblTourBook2TI { get; set; }
    public virtual DbSet<tblTourBook3> tblTourBook3 { get; set; }
    public virtual DbSet<tblTourBook3TI> tblTourBook3TI { get; set; }
    public virtual DbSet<tblTranD> tblTranD { get; set; }
    public virtual DbSet<tblTravelOrder> tblTravelOrder { get; set; }
    public virtual DbSet<C_dta_mv_18> C_dta_mv_18 { get; set; }
    public virtual DbSet<C_dta_mv_40> C_dta_mv_40 { get; set; }
    public virtual DbSet<admin_acc00r> admin_acc00r { get; set; }
    public virtual DbSet<admin_order00> admin_order00 { get; set; }
    public virtual DbSet<admin_order00_1> admin_order00_1 { get; set; }
    public virtual DbSet<admin_order00_cus> admin_order00_cus { get; set; }
    public virtual DbSet<admin_rep_checks> admin_rep_checks { get; set; }
    public virtual DbSet<admin_rep_checks_ck_new_20131024> admin_rep_checks_ck_new_20131024 { get; set; }
    public virtual DbSet<admin_rep_checks_return> admin_rep_checks_return { get; set; }
    public virtual DbSet<admin_rep_expense> admin_rep_expense { get; set; }
    public virtual DbSet<admin_rep_income_fit> admin_rep_income_fit { get; set; }
    public virtual DbSet<admin_rep_income_tour> admin_rep_income_tour { get; set; }
    public virtual DbSet<admin_rep00> admin_rep00 { get; set; }
    public virtual DbSet<admin_rep01> admin_rep01 { get; set; }
    public virtual DbSet<admin_rep02_1> admin_rep02_1 { get; set; }
    public virtual DbSet<admin_rep02_2> admin_rep02_2 { get; set; }
    public virtual DbSet<admin_rep03> admin_rep03 { get; set; }
    public virtual DbSet<admin_rep04> admin_rep04 { get; set; }
    public virtual DbSet<admin_rep04_1> admin_rep04_1 { get; set; }
    public virtual DbSet<admin_repbosschecks> admin_repbosschecks { get; set; }
    public virtual DbSet<admin_sales00_02> admin_sales00_02 { get; set; }
    public virtual DbSet<admin_sales00_03> admin_sales00_03 { get; set; }
    public virtual DbSet<admin_sales00_04> admin_sales00_04 { get; set; }
    public virtual DbSet<admin_sales00_05> admin_sales00_05 { get; set; }
    public virtual DbSet<admin_sales00_06> admin_sales00_06 { get; set; }
    public virtual DbSet<admin_sales00_07> admin_sales00_07 { get; set; }
    public virtual DbSet<admin_sales00_08> admin_sales00_08 { get; set; }
    public virtual DbSet<admin_tourtable> admin_tourtable { get; set; }
    public virtual DbSet<tblDaieiMoney> tblDaieiMoney { get; set; }
    public virtual DbSet<tblMngFile50> tblMngFile50 { get; set; }
    public virtual DbSet<tblOrderCount> tblOrderCount { get; set; }
    public virtual DbSet<tblOrderDeposit> tblOrderDeposit { get; set; }
    public virtual DbSet<tblOrderDueDate> tblOrderDueDate { get; set; }
    public virtual DbSet<tblSalesRec20> tblSalesRec20 { get; set; }
    public virtual DbSet<tblUnionAP> tblUnionAP { get; set; }
    public virtual DbSet<v_apollo2013_hottriplist> v_apollo2013_hottriplist { get; set; }
    public virtual DbSet<v_apollo2013_index> v_apollo2013_index { get; set; }
    public virtual DbSet<v_apollo2013_index_2> v_apollo2013_index_2 { get; set; }
    public virtual DbSet<v_country_promote> v_country_promote { get; set; }
    public virtual DbSet<v_country_suggest> v_country_suggest { get; set; }
    public virtual DbSet<v_gp_index> v_gp_index { get; set; }
    public virtual DbSet<v_index_hottriplist> v_index_hottriplist { get; set; }
    public virtual DbSet<v_index_hottriplist_New> v_index_hottriplist_New { get; set; }
    public virtual DbSet<v_index_onsale> v_index_onsale { get; set; }
    public virtual DbSet<v_kh_country_promote> v_kh_country_promote { get; set; }
    public virtual DbSet<v_kh_country_suggest> v_kh_country_suggest { get; set; }
    public virtual DbSet<v_kh_country_suggest_new> v_kh_country_suggest_new { get; set; }
    public virtual DbSet<v_opt_list> v_opt_list { get; set; }
    public virtual DbSet<v_pchome_ad_promo> v_pchome_ad_promo { get; set; }
    public virtual DbSet<v_pchome_suggested> v_pchome_suggested { get; set; }
    public virtual DbSet<v_Repeater1> v_Repeater1 { get; set; }
    public virtual DbSet<v_Repeater2> v_Repeater2 { get; set; }
    public virtual DbSet<v_search_package_coun> v_search_package_coun { get; set; }
    public virtual DbSet<v_search_result> v_search_result { get; set; }
    public virtual DbSet<v_search_result_browse> v_search_result_browse { get; set; }
    public virtual DbSet<v_search_result_promo> v_search_result_promo { get; set; }
    public virtual DbSet<v_subject> v_subject { get; set; }
    public virtual DbSet<v_subject_2013NY> v_subject_2013NY { get; set; }
    public virtual DbSet<v_subject_casual> v_subject_casual { get; set; }
    public virtual DbSet<v_subject_charter> v_subject_charter { get; set; }
    public virtual DbSet<v_trip_daily> v_trip_daily { get; set; }
    public virtual DbSet<v_trip_daily_browse> v_trip_daily_browse { get; set; }
    public virtual DbSet<v_trip_daily_download> v_trip_daily_download { get; set; }
    public virtual DbSet<v_trip_dailyinfo> v_trip_dailyinfo { get; set; }
    public virtual DbSet<v_trip_info_air> v_trip_info_air { get; set; }
    public virtual DbSet<v_trip_info_hotel> v_trip_info_hotel { get; set; }
    public virtual DbSet<v_trip_list> v_trip_list { get; set; }
    public virtual DbSet<v_trip_list_date> v_trip_list_date { get; set; }
    public virtual DbSet<v_trip_order> v_trip_order { get; set; }
    public virtual DbSet<v_trip_order_complete> v_trip_order_complete { get; set; }
    public virtual DbSet<v_txg_kh_promote> v_txg_kh_promote { get; set; }
    public virtual DbSet<view_ck_test_tidyup_tblap10> view_ck_test_tidyup_tblap10 { get; set; }
    public virtual DbSet<view_ck_test_tidyup_tblap60> view_ck_test_tidyup_tblap60 { get; set; }
    public virtual DbSet<view_ck_tidyup_tblsalesrec> view_ck_tidyup_tblsalesrec { get; set; }
    public virtual DbSet<代轉套表專用> 代轉套表專用 { get; set; }
    public virtual DbSet<錯誤的繳款單> 錯誤的繳款單 { get; set; }
    public virtual DbSet<應收未收列表> 應收未收列表 { get; set; }
    public virtual DbSet<檢查請款單的總額> 檢查請款單的總額 { get; set; }
    public virtual DbSet<檢查繳款單的總額> 檢查繳款單的總額 { get; set; }
    public virtual DbSet<tblProductOptDetail> tblProductOptDetail { get; set; }
    public virtual DbSet<tblDicAttraction> tblDicAttraction { get; set; }
    public virtual DbSet<tblDicImgGroup> tblDicImgGroup { get; set; }
    public virtual DbSet<tblDicImgItem> tblDicImgItem { get; set; }
    public virtual DbSet<tblProAtt> tblProAtt { get; set; }
    public virtual DbSet<tblProductOptP> tblProductOptP { get; set; }
    public virtual DbSet<tblProductOptS> tblProductOptS { get; set; }
    public virtual DbSet<tblProImg> tblProImg { get; set; }
    public virtual DbSet<tblAttImg> tblAttImg { get; set; }
    public virtual DbSet<tblProductDaily> tblProductDaily { get; set; }
    public virtual DbSet<tblProductDailySight> tblProductDailySight { get; set; }
    public virtual DbSet<tblProductQA> tblProductQA { get; set; }
    public virtual DbSet<tblProductSchDaily> tblProductSchDaily { get; set; }
    public virtual DbSet<tblProductSchDailySight> tblProductSchDailySight { get; set; }
    public virtual DbSet<tblProductSchQA> tblProductSchQA { get; set; }
    public virtual DbSet<tblFBMember> tblFBMember { get; set; }
    public virtual DbSet<tblMailGroupDTS> tblMailGroupDTS { get; set; }
    public virtual DbSet<tblMailGroupItemDTS> tblMailGroupItemDTS { get; set; }
    public virtual DbSet<tblHotelPackageCus> tblHotelPackageCus { get; set; }
    public virtual DbSet<tblHotelPackage> tblHotelPackage { get; set; }
    public virtual DbSet<tblCar> tblCar { get; set; }
    public virtual DbSet<tblCarPackage> tblCarPackage { get; set; }
    public virtual DbSet<tblCarPackageD> tblCarPackageD { get; set; }
    public virtual DbSet<tblCarPackageDShuttle> tblCarPackageDShuttle { get; set; }
    public virtual DbSet<tblCoupon> tblCoupon { get; set; }
    public virtual DbSet<tblCouponTable> tblCouponTable { get; set; }
    public virtual DbSet<tblOrderOPRECPAY> tblOrderOPRECPAY { get; set; }
    public virtual DbSet<tblOrderOPRECPAYBack> tblOrderOPRECPAYBack { get; set; }
    public virtual DbSet<tblOrderOPRCC> tblOrderOPRCC { get; set; }
    public virtual DbSet<tblOrderOPR> tblOrderOPR { get; set; }
    public virtual DbSet<tblTourList> tblTourList { get; set; }
    public virtual DbSet<tblTourListTI> tblTourListTI { get; set; }
    public virtual DbSet<tblArticle> tblArticle { get; set; }
    public virtual DbSet<tblEditor> tblEditor { get; set; }
    public virtual DbSet<tblHotelC> tblHotelC { get; set; }
    public virtual DbSet<tblHugtag> tblHugtag { get; set; }
    public virtual DbSet<tblSource> tblSource { get; set; }
    public virtual DbSet<tblSystemConfig> tblSystemConfig { get; set; }
    public virtual DbSet<tblTheIma> tblTheIma { get; set; }
    public virtual DbSet<tblTheme> tblTheme { get; set; }
    public virtual DbSet<tblTopic> tblTopic { get; set; }
    public virtual DbSet<tblActivity> tblActivity { get; set; }
    public virtual DbSet<tblFITPackageItemLog> tblFITPackageItemLog { get; set; }
    public virtual DbSet<tblFITMember> tblFITMember { get; set; }
    public virtual DbSet<tblFITOrder> tblFITOrder { get; set; }
    public virtual DbSet<tblFITOrderItem> tblFITOrderItem { get; set; }
    public virtual DbSet<tblFITOrderPaid> tblFITOrderPaid { get; set; }
    public virtual DbSet<tblFITPackage> tblFITPackage { get; set; }
    public virtual DbSet<tblFITPackageItem> tblFITPackageItem { get; set; }
    public virtual DbSet<tblFITOrderCus> tblFITOrderCus { get; set; }
    public virtual DbSet<tblProductDailyCW> tblProductDailyCW { get; set; }
    public virtual DbSet<tblProductDailySightCW> tblProductDailySightCW { get; set; }

    [DbFunction("DataModel", "Split")]
    public virtual IQueryable<Split_Result> Split(string stringToSplit, string separator)
    {
        var stringToSplitParameter = stringToSplit != null ?
            new ObjectParameter("StringToSplit", stringToSplit) :
            new ObjectParameter("StringToSplit", typeof(string));

        var separatorParameter = separator != null ?
            new ObjectParameter("Separator", separator) :
            new ObjectParameter("Separator", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[DataModel].[Split](@StringToSplit, @Separator)", stringToSplitParameter, separatorParameter);
    }

    public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
    {
        var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
            new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
            new ObjectParameter("vchSourceSafeINI", typeof(string));

        var vchProjectNameParameter = vchProjectName != null ?
            new ObjectParameter("vchProjectName", vchProjectName) :
            new ObjectParameter("vchProjectName", typeof(string));

        var vchCommentParameter = vchComment != null ?
            new ObjectParameter("vchComment", vchComment) :
            new ObjectParameter("vchComment", typeof(string));

        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
    }

    public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
    {
        var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
            new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
            new ObjectParameter("vchSourceSafeINI", typeof(string));

        var vchProjectNameParameter = vchProjectName != null ?
            new ObjectParameter("vchProjectName", vchProjectName) :
            new ObjectParameter("vchProjectName", typeof(string));

        var vchCommentParameter = vchComment != null ?
            new ObjectParameter("vchComment", vchComment) :
            new ObjectParameter("vchComment", typeof(string));

        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
    }

    public virtual int dt_adduserobject()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
    }

    public virtual int dt_adduserobject_vcs(string vchProperty)
    {
        var vchPropertyParameter = vchProperty != null ?
            new ObjectParameter("vchProperty", vchProperty) :
            new ObjectParameter("vchProperty", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
    }

    public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
    {
        var chObjectTypeParameter = chObjectType != null ?
            new ObjectParameter("chObjectType", chObjectType) :
            new ObjectParameter("chObjectType", typeof(string));

        var vchObjectNameParameter = vchObjectName != null ?
            new ObjectParameter("vchObjectName", vchObjectName) :
            new ObjectParameter("vchObjectName", typeof(string));

        var vchCommentParameter = vchComment != null ?
            new ObjectParameter("vchComment", vchComment) :
            new ObjectParameter("vchComment", typeof(string));

        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        var iVCSFlagsParameter = iVCSFlags.HasValue ?
            new ObjectParameter("iVCSFlags", iVCSFlags) :
            new ObjectParameter("iVCSFlags", typeof(int));

        var iActionFlagParameter = iActionFlag.HasValue ?
            new ObjectParameter("iActionFlag", iActionFlag) :
            new ObjectParameter("iActionFlag", typeof(int));

        var txStream1Parameter = txStream1 != null ?
            new ObjectParameter("txStream1", txStream1) :
            new ObjectParameter("txStream1", typeof(string));

        var txStream2Parameter = txStream2 != null ?
            new ObjectParameter("txStream2", txStream2) :
            new ObjectParameter("txStream2", typeof(string));

        var txStream3Parameter = txStream3 != null ?
            new ObjectParameter("txStream3", txStream3) :
            new ObjectParameter("txStream3", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
    }

    public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
    {
        var chObjectTypeParameter = chObjectType != null ?
            new ObjectParameter("chObjectType", chObjectType) :
            new ObjectParameter("chObjectType", typeof(string));

        var vchObjectNameParameter = vchObjectName != null ?
            new ObjectParameter("vchObjectName", vchObjectName) :
            new ObjectParameter("vchObjectName", typeof(string));

        var vchCommentParameter = vchComment != null ?
            new ObjectParameter("vchComment", vchComment) :
            new ObjectParameter("vchComment", typeof(string));

        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        var iVCSFlagsParameter = iVCSFlags.HasValue ?
            new ObjectParameter("iVCSFlags", iVCSFlags) :
            new ObjectParameter("iVCSFlags", typeof(int));

        var iActionFlagParameter = iActionFlag.HasValue ?
            new ObjectParameter("iActionFlag", iActionFlag) :
            new ObjectParameter("iActionFlag", typeof(int));

        var txStream1Parameter = txStream1 != null ?
            new ObjectParameter("txStream1", txStream1) :
            new ObjectParameter("txStream1", typeof(string));

        var txStream2Parameter = txStream2 != null ?
            new ObjectParameter("txStream2", txStream2) :
            new ObjectParameter("txStream2", typeof(string));

        var txStream3Parameter = txStream3 != null ?
            new ObjectParameter("txStream3", txStream3) :
            new ObjectParameter("txStream3", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
    }

    public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
    {
        var chObjectTypeParameter = chObjectType != null ?
            new ObjectParameter("chObjectType", chObjectType) :
            new ObjectParameter("chObjectType", typeof(string));

        var vchObjectNameParameter = vchObjectName != null ?
            new ObjectParameter("vchObjectName", vchObjectName) :
            new ObjectParameter("vchObjectName", typeof(string));

        var vchCommentParameter = vchComment != null ?
            new ObjectParameter("vchComment", vchComment) :
            new ObjectParameter("vchComment", typeof(string));

        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        var iVCSFlagsParameter = iVCSFlags.HasValue ?
            new ObjectParameter("iVCSFlags", iVCSFlags) :
            new ObjectParameter("iVCSFlags", typeof(int));

        var iActionFlagParameter = iActionFlag.HasValue ?
            new ObjectParameter("iActionFlag", iActionFlag) :
            new ObjectParameter("iActionFlag", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
    }

    public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
    {
        var chObjectTypeParameter = chObjectType != null ?
            new ObjectParameter("chObjectType", chObjectType) :
            new ObjectParameter("chObjectType", typeof(string));

        var vchObjectNameParameter = vchObjectName != null ?
            new ObjectParameter("vchObjectName", vchObjectName) :
            new ObjectParameter("vchObjectName", typeof(string));

        var vchCommentParameter = vchComment != null ?
            new ObjectParameter("vchComment", vchComment) :
            new ObjectParameter("vchComment", typeof(string));

        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        var iVCSFlagsParameter = iVCSFlags.HasValue ?
            new ObjectParameter("iVCSFlags", iVCSFlags) :
            new ObjectParameter("iVCSFlags", typeof(int));

        var iActionFlagParameter = iActionFlag.HasValue ?
            new ObjectParameter("iActionFlag", iActionFlag) :
            new ObjectParameter("iActionFlag", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
    }

    public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
    {
        var iObjectParameter = iObject.HasValue ?
            new ObjectParameter("iObject", iObject) :
            new ObjectParameter("iObject", typeof(int));

        var iresultParameter = iresult.HasValue ?
            new ObjectParameter("iresult", iresult) :
            new ObjectParameter("iresult", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
    }

    public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
    {
        var iObjectParameter = iObject.HasValue ?
            new ObjectParameter("iObject", iObject) :
            new ObjectParameter("iObject", typeof(int));

        var iresultParameter = iresult.HasValue ?
            new ObjectParameter("iresult", iresult) :
            new ObjectParameter("iresult", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
    }

    public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        var propertyParameter = property != null ?
            new ObjectParameter("property", property) :
            new ObjectParameter("property", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
    }

    public virtual int dt_dropuserobjectbyid(Nullable<int> id)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
    }

    public virtual int dt_generateansiname(ObjectParameter name)
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
    }

    public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
    {
        var propertyParameter = property != null ?
            new ObjectParameter("property", property) :
            new ObjectParameter("property", typeof(string));

        var valueParameter = value != null ?
            new ObjectParameter("value", value) :
            new ObjectParameter("value", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
    }

    public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
    {
        var propertyParameter = property != null ?
            new ObjectParameter("property", property) :
            new ObjectParameter("property", typeof(string));

        var uvalueParameter = uvalue != null ?
            new ObjectParameter("uvalue", uvalue) :
            new ObjectParameter("uvalue", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
    }

    public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        var propertyParameter = property != null ?
            new ObjectParameter("property", property) :
            new ObjectParameter("property", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
    }

    public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        var propertyParameter = property != null ?
            new ObjectParameter("property", property) :
            new ObjectParameter("property", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
    }

    public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        var propertyParameter = property != null ?
            new ObjectParameter("property", property) :
            new ObjectParameter("property", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
    }

    public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        var propertyParameter = property != null ?
            new ObjectParameter("property", property) :
            new ObjectParameter("property", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
    }

    public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
    {
        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        var iWhoTooParameter = iWhoToo.HasValue ?
            new ObjectParameter("iWhoToo", iWhoToo) :
            new ObjectParameter("iWhoToo", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
    }

    public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
    {
        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        var iWhoTooParameter = iWhoToo.HasValue ?
            new ObjectParameter("iWhoToo", iWhoToo) :
            new ObjectParameter("iWhoToo", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
    }

    public virtual int dt_removefromsourcecontrol()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
    }

    public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        var propertyParameter = property != null ?
            new ObjectParameter("property", property) :
            new ObjectParameter("property", typeof(string));

        var valueParameter = value != null ?
            new ObjectParameter("value", value) :
            new ObjectParameter("value", typeof(string));

        var lvalueParameter = lvalue != null ?
            new ObjectParameter("lvalue", lvalue) :
            new ObjectParameter("lvalue", typeof(byte[]));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
    }

    public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        var propertyParameter = property != null ?
            new ObjectParameter("property", property) :
            new ObjectParameter("property", typeof(string));

        var uvalueParameter = uvalue != null ?
            new ObjectParameter("uvalue", uvalue) :
            new ObjectParameter("uvalue", typeof(string));

        var lvalueParameter = lvalue != null ?
            new ObjectParameter("lvalue", lvalue) :
            new ObjectParameter("lvalue", typeof(byte[]));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
    }

    public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
    {
        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
    }

    public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
    {
        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
    }

    public virtual int dt_vcsenabled()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
    }

    public virtual ObjectResult<Nullable<int>> dt_verstamp006()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
    }

    public virtual ObjectResult<Nullable<int>> dt_verstamp007()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
    }

    public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
    {
        var chObjectTypeParameter = chObjectType != null ?
            new ObjectParameter("chObjectType", chObjectType) :
            new ObjectParameter("chObjectType", typeof(string));

        var vchObjectNameParameter = vchObjectName != null ?
            new ObjectParameter("vchObjectName", vchObjectName) :
            new ObjectParameter("vchObjectName", typeof(string));

        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
    }

    public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
    {
        var chObjectTypeParameter = chObjectType != null ?
            new ObjectParameter("chObjectType", chObjectType) :
            new ObjectParameter("chObjectType", typeof(string));

        var vchObjectNameParameter = vchObjectName != null ?
            new ObjectParameter("vchObjectName", vchObjectName) :
            new ObjectParameter("vchObjectName", typeof(string));

        var vchLoginNameParameter = vchLoginName != null ?
            new ObjectParameter("vchLoginName", vchLoginName) :
            new ObjectParameter("vchLoginName", typeof(string));

        var vchPasswordParameter = vchPassword != null ?
            new ObjectParameter("vchPassword", vchPassword) :
            new ObjectParameter("vchPassword", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
    }

    public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));

        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }

    public virtual int sp_convert_view_to_table()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_convert_view_to_table");
    }

    public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));

        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }

    public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
    }

    public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
    }

    public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
    }

    public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        var new_diagramnameParameter = new_diagramname != null ?
            new ObjectParameter("new_diagramname", new_diagramname) :
            new ObjectParameter("new_diagramname", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
    }

    public virtual int sp_upgraddiagrams()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
    }

    public virtual ObjectResult<UserSP_SearchTables_Result> UserSP_SearchTables(string tablenames, string searchStr, Nullable<bool> generateSQLOnly)
    {
        var tablenamesParameter = tablenames != null ?
            new ObjectParameter("Tablenames", tablenames) :
            new ObjectParameter("Tablenames", typeof(string));

        var searchStrParameter = searchStr != null ?
            new ObjectParameter("SearchStr", searchStr) :
            new ObjectParameter("SearchStr", typeof(string));

        var generateSQLOnlyParameter = generateSQLOnly.HasValue ?
            new ObjectParameter("GenerateSQLOnly", generateSQLOnly) :
            new ObjectParameter("GenerateSQLOnly", typeof(bool));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserSP_SearchTables_Result>("UserSP_SearchTables", tablenamesParameter, searchStrParameter, generateSQLOnlyParameter);
    }
}
