//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ODB_DTSEntities : DbContext
{
    public ODB_DTSEntities()
        : base("name=ODB_DTSEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<OTB_SYS_ArgumentClass> OTB_SYS_ArgumentClass { get; set; }
    public virtual DbSet<OTB_SYS_Arguments> OTB_SYS_Arguments { get; set; }
    public virtual DbSet<OTB_SYS_Attachments> OTB_SYS_Attachments { get; set; }
    public virtual DbSet<OTB_SYS_Departments> OTB_SYS_Departments { get; set; }
    public virtual DbSet<OTB_SYS_Document> OTB_SYS_Document { get; set; }
    public virtual DbSet<OTB_SYS_Document_Temp> OTB_SYS_Document_Temp { get; set; }
    public virtual DbSet<OTB_SYS_Document_Trash> OTB_SYS_Document_Trash { get; set; }
    public virtual DbSet<OTB_SYS_Email> OTB_SYS_Email { get; set; }
    public virtual DbSet<OTB_SYS_Emaillog> OTB_SYS_Emaillog { get; set; }
    public virtual DbSet<OTB_SYS_EmaillogTemp> OTB_SYS_EmaillogTemp { get; set; }
    public virtual DbSet<OTB_SYS_EmailSetting> OTB_SYS_EmailSetting { get; set; }
    public virtual DbSet<OTB_SYS_MembersBase> OTB_SYS_MembersBase { get; set; }
    public virtual DbSet<OTB_SYS_MembersToRule> OTB_SYS_MembersToRule { get; set; }
    public virtual DbSet<OTB_SYS_ProgramList> OTB_SYS_ProgramList { get; set; }
    public virtual DbSet<OTB_SYS_Rules> OTB_SYS_Rules { get; set; }
    public virtual DbSet<OTB_SYS_SystemSetting> OTB_SYS_SystemSetting { get; set; }
    public virtual DbSet<OTB_SYS_Authorize> OTB_SYS_Authorize { get; set; }
    public virtual DbSet<OTB_SYS_Log> OTB_SYS_Log { get; set; }
    public virtual DbSet<OTB_SYS_MaxNumber> OTB_SYS_MaxNumber { get; set; }
    public virtual DbSet<OTB_SYS_ModuleList> OTB_SYS_ModuleList { get; set; }
    public virtual DbSet<OTB_SYS_PersonalGridManage> OTB_SYS_PersonalGridManage { get; set; }
    public virtual DbSet<OTB_SYS_TableDirectory> OTB_SYS_TableDirectory { get; set; }
}
