//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class OTB_SYS_ArgumentClass
{
    public string ArgumentClassID { get; set; }
    public string ArgumentClassName { get; set; }
    public Nullable<int> MaxNumberClass { get; set; }
    public Nullable<int> MaxNumberCatData { get; set; }
    public Nullable<int> OrderByValue { get; set; }
    public string Effective { get; set; }
    public string DelStatus { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_Arguments
{
    public string ArgumentClassID { get; set; }
    public string ArgumentID { get; set; }
    public string ArgumentValue { get; set; }
    public Nullable<int> MaxNumber { get; set; }
    public Nullable<int> OrderByValue { get; set; }
    public string DelStatus { get; set; }
    public string Effective { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_Attachments
{
    public string TargetRelationID { get; set; }
    public string SourceRelationID { get; set; }
    public string FileName { get; set; }
    public string SubFileName { get; set; }
    public string FilePath { get; set; }
    public Nullable<int> FileSize { get; set; }
    public byte[] FileContent { get; set; }
    public string FileType { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_Authorize
{
    public string RuleID { get; set; }
    public string ProgramID { get; set; }
    public string AllowRight { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_Departments
{
    public string DepartmentID { get; set; }
    public string DepartmentName { get; set; }
    public string DepartmentShortName { get; set; }
    public string ChiefOfDepartmentID { get; set; }
    public Nullable<int> LevelOfDepartment { get; set; }
    public string NameOfLevel { get; set; }
    public string ParentDepartmentID { get; set; }
    public Nullable<int> OrderByValue { get; set; }
    public string Effective { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
    public string DelStatus { get; set; }
    public string CustomerType { get; set; }
    public string IsOutside { get; set; }
}

public partial class OTB_SYS_Document
{
    public string GUID { get; set; }
    public string FileName { get; set; }
    public string FileNumber { get; set; }
    public string CFName { get; set; }
    public string EFName { get; set; }
    public string SubFileName { get; set; }
    public string SightTitle { get; set; }
    public string SightContent { get; set; }
    public string SightKeyWord { get; set; }
    public string FileRoot { get; set; }
    public string FilePath { get; set; }
    public Nullable<int> FileSize { get; set; }
    public Nullable<int> PixelW { get; set; }
    public Nullable<int> PixelH { get; set; }
    public string FileContent { get; set; }
    public string IsProtected { get; set; }
    public string IsPublic { get; set; }
    public string Memo { get; set; }
    public Nullable<System.DateTime> FileCreateDate { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
    public Nullable<int> status { get; set; }
}

public partial class OTB_SYS_Document_Temp
{
    public string GUID { get; set; }
    public string FileName { get; set; }
    public string FileNumber { get; set; }
    public string CFName { get; set; }
    public string EFName { get; set; }
    public string SubFileName { get; set; }
    public string SightTitle { get; set; }
    public string SightContent { get; set; }
    public string SightKeyWord { get; set; }
    public string FileRoot { get; set; }
    public string FilePath { get; set; }
    public Nullable<int> FileSize { get; set; }
    public Nullable<int> PixelW { get; set; }
    public Nullable<int> PixelH { get; set; }
    public string FileContent { get; set; }
    public string IsProtected { get; set; }
    public string IsPublic { get; set; }
    public string Memo { get; set; }
    public Nullable<System.DateTime> FileCreateDate { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
    public Nullable<int> status { get; set; }
}

public partial class OTB_SYS_Document_Trash
{
    public string GUID { get; set; }
    public string FileName { get; set; }
    public string FileNumber { get; set; }
    public string CFName { get; set; }
    public string EFName { get; set; }
    public string SubFileName { get; set; }
    public string SightTitle { get; set; }
    public string SightContent { get; set; }
    public string SightKeyWord { get; set; }
    public string FileRoot { get; set; }
    public string FilePath { get; set; }
    public Nullable<int> FileSize { get; set; }
    public Nullable<int> PixelW { get; set; }
    public Nullable<int> PixelH { get; set; }
    public string FileContent { get; set; }
    public string IsProtected { get; set; }
    public string IsPublic { get; set; }
    public string Memo { get; set; }
    public Nullable<System.DateTime> FileCreateDate { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
    public Nullable<int> status { get; set; }
}

public partial class OTB_SYS_Email
{
    public string EmailID { get; set; }
    public string Type { get; set; }
    public string EmailName { get; set; }
    public string EmailDescript { get; set; }
    public string EmailSubject { get; set; }
    public string BodyHtml { get; set; }
    public string BodyHtml_tw { get; set; }
    public string BodyHtml_cn { get; set; }
    public string Variable { get; set; }
    public string BCC { get; set; }
    public string Refemail { get; set; }
    public string chkdul { get; set; }
    public Nullable<short> Notification { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_Emaillog
{
    public int id { get; set; }
    public string EmailID { get; set; }
    public string MsgID { get; set; }
    public string UserID { get; set; }
    public string PaxCD { get; set; }
    public string mailto { get; set; }
    public string mailsubject { get; set; }
    public string mailmsg { get; set; }
    public Nullable<System.DateTime> maildatetime { get; set; }
    public string StatusCode { get; set; }
    public Nullable<bool> Success { get; set; }
}

public partial class OTB_SYS_EmaillogTemp
{
    public int id { get; set; }
    public string EmailID { get; set; }
    public string MsgID { get; set; }
    public string UserID { get; set; }
    public string PaxCD { get; set; }
    public string mailto { get; set; }
    public string mailsubject { get; set; }
    public string mailmsg { get; set; }
    public Nullable<System.DateTime> maildatetime { get; set; }
    public string StatusCode { get; set; }
    public Nullable<bool> Success { get; set; }
}

public partial class OTB_SYS_EmailSetting
{
    public string EmailID { get; set; }
    public string SmtpHost { get; set; }
    public string UserName { get; set; }
    public string UserId { get; set; }
    public string PassWord { get; set; }
    public string ShowAddreess { get; set; }
    public Nullable<int> Port { get; set; }
    public Nullable<int> TimeOut { get; set; }
    public string EnableSSL { get; set; }
    public string AnonymousAuthentication { get; set; }
    public string MailEncoding { get; set; }
    public string Memo { get; set; }
    public string Effective { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_Log
{
    public int Id { get; set; }
    public System.DateTime Date { get; set; }
    public string Thread { get; set; }
    public string Level { get; set; }
    public string Logger { get; set; }
    public string Message { get; set; }
    public string Exception { get; set; }
}

public partial class OTB_SYS_MaxNumber
{
    public string Type { get; set; }
    public string CountYear { get; set; }
    public string CountMonth { get; set; }
    public string CountDay { get; set; }
    public Nullable<int> CountMax { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_MembersBase
{
    public string MemberID { get; set; }
    public string MemberPwd { get; set; }
    public string MemberName { get; set; }
    public string ContectEmail { get; set; }
    public string Contect { get; set; }
    public string ContectTEL { get; set; }
    public string ContectExt { get; set; }
    public string ContectFax { get; set; }
    public string ContectCell { get; set; }
    public string ContectAddress { get; set; }
    public Nullable<System.DateTime> BirthDate { get; set; }
    public Nullable<System.DateTime> ArriveDate { get; set; }
    public string JobtitleID { get; set; }
    public string DeptID { get; set; }
    public string Ext { get; set; }
    public Nullable<System.DateTime> LeaveDate { get; set; }
    public string CalColor { get; set; }
    public string Effective { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_MembersToRule
{
    public string MemberID { get; set; }
    public string RuleID { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_ModuleList
{
    public string ModuleID { get; set; }
    public string ModuleName { get; set; }
    public string ParentID { get; set; }
    public Nullable<int> ClassCount { get; set; }
    public Nullable<int> OrderByValue { get; set; }
    public string BgCss { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_PersonalGridManage
{
    public string Grid_Id { get; set; }
    public string GridTitle { get; set; }
    public string PageName { get; set; }
    public string TableName { get; set; }
    public string DataField { get; set; }
    public string FieldName { get; set; }
    public string QueryField { get; set; }
    public string QueryName { get; set; }
    public string QueryType { get; set; }
    public string QueryDefault { get; set; }
    public string QueryWidth { get; set; }
    public string GridSetting { get; set; }
    public string sort_Order { get; set; }
    public string sort { get; set; }
    public string columnWidth { get; set; }
    public string columnAlign { get; set; }
    public string queryCondition { get; set; }
    public string Type { get; set; }
    public string Effective { get; set; }
    public Nullable<int> limitCount { get; set; }
    public Nullable<int> Pager { get; set; }
    public string GoToUrl { get; set; }
    public string GoToParam { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_ProgramList
{
    public string ProgramID { get; set; }
    public string ProgramName { get; set; }
    public string ModuleID { get; set; }
    public string FilePath { get; set; }
    public string ImgPath { get; set; }
    public string AllowRight { get; set; }
    public Nullable<int> OrderByValue { get; set; }
    public string ProgramType { get; set; }
    public string BgCss { get; set; }
    public string grouptag { get; set; }
    public string Effective { get; set; }
    public string ShowInList { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
    public string MainTableName { get; set; }
}

public partial class OTB_SYS_Rules
{
    public string RuleID { get; set; }
    public string RuleName { get; set; }
    public string DelStatus { get; set; }
    public string Memo { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_SystemSetting
{
    public string SettingItem { get; set; }
    public string SettingDescription { get; set; }
    public string SettingValue { get; set; }
    public string Memo { get; set; }
    public string Effective { get; set; }
    public string CreateUser { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyUser { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class OTB_SYS_TableDirectory
{
    public string form_id { get; set; }
    public Nullable<short> page_no { get; set; }
    public string data_field { get; set; }
    public string data_label { get; set; }
    public Nullable<short> data_size { get; set; }
    public string data_slabel { get; set; }
    public string data_type { get; set; }
    public string is_key { get; set; }
    public string is_nullable { get; set; }
    public bool data_lock { get; set; }
    public string data_default { get; set; }
    public string data_process { get; set; }
    public string data_check { get; set; }
    public string data_help_msg { get; set; }
    public string link_tb { get; set; }
    public string link_field { get; set; }
    public string dhelp_form { get; set; }
    public string link_index { get; set; }
    public string data_control { get; set; }
    public Nullable<short> data_control_idx { get; set; }
    public string data_control_value { get; set; }
    public Nullable<int> data_seqno { get; set; }
    public bool data_dcontrol { get; set; }
    public string link_proc { get; set; }
    public bool link_join { get; set; }
    public string linked_field { get; set; }
    public Nullable<short> data_control_width { get; set; }
    public Nullable<short> data_control_left { get; set; }
    public string data_input_mask { get; set; }
    public bool data_updown { get; set; }
    public bool data_mask_included { get; set; }
    public Nullable<short> data_control_top { get; set; }
    public Nullable<short> data_control_height { get; set; }
    public Nullable<short> data_label_height { get; set; }
    public Nullable<short> data_label_top { get; set; }
    public Nullable<short> data_label_width { get; set; }
    public Nullable<short> data_label_left { get; set; }
    public string data_control_svalue { get; set; }
    public Nullable<short> data_decm { get; set; }
    public bool SEQ_FG { get; set; }
    public bool AUTO_SQ { get; set; }
    public Nullable<short> CN_data_size { get; set; }
    public Nullable<short> CN_data_decm { get; set; }
}
